In [5]:
import pandas as pd
df=pd.read_csv("C:\\Users\\tirumaleswarasai.t\\Desktop\\pokemon_data.csv")
df

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

In [8]:
rows,coloumns = df.shape
rows
coloumns

12

In [9]:
df[50:71]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
50,45,Vileplume,Grass,Poison,75,80,85,110,90,50,1,False
51,46,Paras,Bug,Grass,35,70,55,45,55,25,1,False
52,47,Parasect,Bug,Grass,60,95,80,60,80,30,1,False
53,48,Venonat,Bug,Poison,60,55,50,40,55,45,1,False
54,49,Venomoth,Bug,Poison,70,65,60,90,75,90,1,False
55,50,Diglett,Ground,NaN,10,55,25,35,45,95,1,False
56,51,Dugtrio,Ground,NaN,35,80,50,50,70,120,1,False
57,52,Meowth,Normal,NaN,40,45,35,40,40,90,1,False
58,53,Persian,Normal,NaN,65,70,60,65,65,115,1,False
59,54,Psyduck,Water,NaN,50,52,48,65,50,55,1,False
60,55,Golduck,Water,NaN,80,82,78,95,80,85,1,False
61,56,Mankey,Fighting,NaN,40,80,35,35,45,70,1,False
62,57,Primeape,Fighting,NaN,65,105,60,60,70,95,1,False
63,58,Growlithe,Fire,NaN,55,70,45,70,50,60,1,False
64,59,Arcanine,Fire,NaN,90,110,80,100,80,95,1,False
65,60,Poliwag,Water,NaN,40,50,40,40,40,90,1,False
66,61,Poliwhirl,Water,NaN,65,65,65,50,50,90,1,False
67,62,Poliwrath,Water,Fighting,90,95,95,70,90,70,1,False
68,63,Abra,Psychic,NaN,25,20,15,105,55,90,1,False
69,64,Kadabra,Psychic,NaN,40,35,30,120,70,105,1,False
70,65,Alakazam,Psychic,NaN,55,50,45,135,95,120,1,False

In [13]:
df.columns

Index(['#', 'Name', 'Type 1', 'Type 2', 'HP', 'Attack', 'Defense', 'Sp. Atk',
       'Sp. Def', 'Speed', 'Generation', 'Legendary'],
      dtype='object')

In [19]:
df['Name'][10:51]

10                  Wartortle
11                  Blastoise
12    BlastoiseMega Blastoise
13                   Caterpie
14                    Metapod
15                 Butterfree
16                     Weedle
17                     Kakuna
18                   Beedrill
19      BeedrillMega Beedrill
20                     Pidgey
21                  Pidgeotto
22                    Pidgeot
23        PidgeotMega Pidgeot
24                    Rattata
25                   Raticate
26                    Spearow
27                     Fearow
28                      Ekans
29                      Arbok
30                    Pikachu
31                     Raichu
32                  Sandshrew
33                  Sandslash
34           Nidoran (Female)
35                   Nidorina
36                  Nidoqueen
37             Nidoran (Male)
38                   Nidorino
39                   Nidoking
40                   Clefairy
41                   Clefable
42                     Vulpix
43                  Ninetales
44                 Jigglypuff
45                 Wigglytuff
46                      Zubat
47                     Golbat
48                     Oddish
49                      Gloom
50                  Vileplume
Name: Name, dtype: object

In [21]:
df[['Name','Defense','Legendary']][10:51]

                       Name  Defense  Legendary
10                Wartortle       80      False
11                Blastoise      100      False
12  BlastoiseMega Blastoise      120      False
13                 Caterpie       35      False
14                  Metapod       55      False
15               Butterfree       50      False
16                   Weedle       30      False
17                   Kakuna       50      False
18                 Beedrill       40      False
19    BeedrillMega Beedrill       40      False
20                   Pidgey       40      False
21                Pidgeotto       55      False
22                  Pidgeot       75      False
23      PidgeotMega Pidgeot       80      False
24                  Rattata       35      False
25                 Raticate       60      False
26                  Spearow       30      False
27                   Fearow       65      False
28                    Ekans       44      False
29                    Arbok       69      False
30                  Pikachu       40      False
31                   Raichu       55      False
32                Sandshrew       85      False
33                Sandslash      110      False
34         Nidoran (Female)       52      False
35                 Nidorina       67      False
36                Nidoqueen       87      False
37           Nidoran (Male)       40      False
38                 Nidorino       57      False
39                 Nidoking       77      False
40                 Clefairy       48      False
41                 Clefable       73      False
42                   Vulpix       40      False
43                Ninetales       75      False
44               Jigglypuff       20      False
45               Wigglytuff       45      False
46                    Zubat       35      False
47                   Golbat       70      False
48                   Oddish       55      False
49                    Gloom       70      False
50                Vileplume       85      False

In [32]:
df['Speed'].max()
df['Speed'].min()
df['Speed'].mean()
df['Speed'].describe() #gives a quick statiscs report like mean, std.deviation,min,max etc on the selected parameter

count    800.000000
mean      68.277500
std       29.060474
min        5.000000
25%       45.000000
50%       65.000000
75%       90.000000
max      180.000000
Name: Speed, dtype: float64

In [35]:
df[df.Legendary == True]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
156,144,Articuno,Ice,Flying,90,85,100,95,125,85,1,True
157,145,Zapdos,Electric,Flying,90,90,85,125,90,100,1,True
158,146,Moltres,Fire,Flying,90,100,90,125,85,90,1,True
162,150,Mewtwo,Psychic,NaN,106,110,90,154,90,130,1,True
163,150,MewtwoMega Mewtwo X,Psychic,Fighting,106,190,100,154,100,130,1,True
...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

In [45]:
df[df.Speed == df.Speed.max()] #Give me the row where df.speed is maximum
#To print only the name of the pokemon which has maximum speed
df['Name'][df.Speed == df['Speed'].max()]
#To print only the name of the pokemon which has minimum speed
df[['Name','Type 1']][df.Speed == df['Speed'].min()]

         Name  Type 1
230   Shuckle     Bug
495  Munchlax  Normal

In [60]:
# To set one of the existing columns as Index
df.set_index('Type 1',inplace=True) #inPlace=True modifies the existing csv file
df

,#,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
Type 1,,,,,,,,,
Grass,1,45,49,49,65,65,45,1,False
Grass,2,60,62,63,80,80,60,1,False
Grass,3,80,82,83,100,100,80,1,False
Grass,3,80,100,123,122,120,80,1,False
Fire,4,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...
Rock,719,50,100,150,100,150,50,6,True
Rock,719,50,160,110,160,110,110,6,True
Psychic,720,80,110,60,150,130,70,6,True
Psychic,720,80,160,60,170,130,80,6,True
Fire,721,80,110,120,130,90,70,6,True

In [61]:
df.loc['Rock']

,#,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
Type 1,,,,,,,,,
Rock,74,40,80,100,30,30,20,1,False
Rock,75,55,95,115,45,45,35,1,False
Rock,76,80,120,130,55,65,45,1,False
Rock,95,35,45,160,30,45,70,1,False
Rock,138,35,40,100,90,55,35,1,False
Rock,139,70,60,125,115,70,55,1,False
Rock,140,30,80,90,55,45,55,1,False
Rock,141,60,115,105,65,70,80,1,False
Rock,142,80,105,65,60,75,130,1,False
Rock,142,80,135,85,70,95,150,1,False
Rock,185,70,100,115,30,65,30,2,False
Rock,246,50,64,50,45,50,41,2,False
Rock,247,70,84,70,65,70,51,2,False
Rock,248,100,134,110,95,100,61,2,False
Rock,248,100,164,150,95,120,71,2,False
Rock,299,30,45,135,45,90,30,3,False
Rock,337,70,55,65,95,85,70,3,False
Rock,338,70,95,85,55,65,70,3,False
Rock,345,66,41,77,61,87,23,3,False
Rock,346,86,81,97,81,107,43,3,False
Rock,347,45,95,50,40,50,75,3,False
Rock,348,75,125,100,70,80,45,3,False
Rock,377,80,100,200,50,100,50,3,True
Rock,408,67,125,40,30,30,58,4,False
Rock,409,97,165,60,65,50,58,4,False
Rock,410,30,42,118,42,88,30,4,False
Rock,411,60,52,168,47,138,30,4,False
Rock,438,50,80,95,10,45,10,4,False
Rock,476,60,55,145,75,150,40,4,False
Rock,524,55,75,85,25,25,15,5,False
Rock,525,70,105,105,50,40,20,5,False
Rock,526,85,135,130,60,80,25,5,False
Rock,566,55,112,45,74,45,70,5,False
Rock,567,75,140,65,112,65,110,5,False
Rock,639,91,129,90,72,90,108,5,True
Rock,688,42,52,67,39,56,50,6,False
Rock,689,72,105,115,54,86,68,6,False
Rock,696,58,89,77,45,45,48,6,False
Rock,697,82,121,119,69,59,71,6,False
Rock,698,77,59,50,67,63,46,6,False
Rock,699,123,77,72,99,92,58,6,False
Rock,703,50,50,150,50,150,50,6,False
Rock,719,50,100,150,100,150,50,6,True
Rock,719,50,160,110,160,110,110,6,True